TreasureSweep/Models/Game.cs
using System;
using Newtonsoft.Json;

namespace TreasureSweepGame.Models
{
  public class Game
  {
    public int GameId { get; set; }
    public int P1Id { get; set; }
    public string P1Name { get; set; }
    public int P2Id { get; set; }
    public string P2Name { get; set; }
    public int CurrentPlayer { get; set; }
    public int TurnCount { get; set; } = 0;
    public bool IsComplete { get; set; } = false;
    public int WinningPlayer { get; set; }
    public string P1Board { get; set; }
    public string P2Board { get; set; }
    public DateTime LastPlayed { get; set; }

    public Game()
    {
      P1Board = generateBoard();
      P2Board = generateBoard();

      // 0 = empty space
      // 1 = chest
      // 2 = mine
      // 3 = miss
      // 4 = hit
      // 5 = hit mine

    }

    public static string generateBoard()
    {
      int numberOfTreasures = 5;

      //Generate empty board
      int[,] board = new int[5, 5];
      for (int y = 0; y < 5; y++)
      {
        for (int x = 0; x < 5; x++)
        {
          board[x, y] = 0;
        }
      }

      //Add treasure to the board
      for (int i = 0; i < numberOfTreasures; i++)
      {
        Random rnd = new Random();
        int x = rnd.Next(0, 5);
        int y = rnd.Next(0, 5);
        if (board[x, y] != 1)
        {
          board[x, y] = 1;
        }
        else
        {
          i--;
        }
      }
      bool done = false;
      //Add mine to board
      while (done == false)
      {
        Random rnd = new Random();
        int mineX = rnd.Next(0, 5);
        int mineY = rnd.Next(0, 5);
        if (board[mineX, mineY] == 0)
        {
          board[mineX, mineY] = 2;
          done = true;
        }
      }
      //convert board to JSON format
      string boardJson = JsonConvert.SerializeObject(board);
      return boardJson;
    }

    public static int[,] Scrub(int[,] board)
    {
      int[,] results = board;
      for (int y = 0; y <= 4; y++)
      {
        for (int x = 0; x <= 4; x++)
        {
          if (results[x, y] <= 2)
          {
            results[x, y] = 0;
          }
        }
      }
      return results;
    }

    public int[,] TakeTurn(int x, int y, int currentPlayerId)
    {
      if (this.P1Id == currentPlayerId)
      {
        int[,] p2Board = JsonConvert.DeserializeObject<int[,]>(this.P2Board);
        if (p2Board[x, y] == 0)
        {
          p2Board[x, y] = 3;
        }
        else if (p2Board[x, y] == 1)
        {
          p2Board[x, y] = 4;
        }
        else if (p2Board[x, y] == 2)
        {
          p2Board[x, y] = 5;
          this.IsComplete = true;
          this.WinningPlayer = this.P2Id;
        }
        if (this.CheckWin(p2Board))
        {
          this.IsComplete = true;
          this.WinningPlayer = this.P1Id;
        }
        DateTime now = DateTime.Now;
        this.LastPlayed = now;
        return p2Board;
      }
      else
      {
        int[,] p1Board = JsonConvert.DeserializeObject<int[,]>(this.P1Board);
        if (p1Board[x, y] == 0)
        {
          p1Board[x, y] = 3;
        }
        else if (p1Board[x, y] == 1)
        {
          p1Board[x, y] = 4;
        }
        else if (p1Board[x, y] == 2)
        {
          p1Board[x, y] = 5;
          this.IsComplete = true;
          this.WinningPlayer = this.P1Id;
        }
        if (this.CheckWin(p1Board))
        {
          this.IsComplete = true;
          this.WinningPlayer = this.P2Id;
        }
        DateTime now = DateTime.Now;
        this.LastPlayed = now;
        return p1Board;
      }
    }

    public bool CheckWin(int[,] board)
    {
      int hitCount = 0;
      for (int x = 0; x < 5; x++)
      {
        for (int y = 0; y < 5; y++)
        {
          if (board[x, y] == 4)
          {
            hitCount++;
          }
        }
      }
      if (hitCount >= 5)
      {
        return true;
      }
      else
      {
        return false;
      }
    }
  }
}

TreasureSweep/Controllers/GamesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using TreasureSweepGame.Models;
using TreasureSweepGame.ViewModels;
using System.Security.Claims;
using Newtonsoft.Json;

namespace TeasureSweepGame.Controllers
{
  [Authorize]
  public class GamesController : Controller
  {
    private readonly TreasureSweepGameContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public GamesController(TreasureSweepGameContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Profile> players = _db.Profiles.ToList();
      List<KeyValuePair<string, int>> leaders = new List<KeyValuePair<string, int>>();
      foreach (Profile player in players)
      {
        int wins = 0;
        int completedGames = 0;
        player.Games = _db.Games.Where(entry => entry.P1Id == player.ProfileId || entry.P2Id == player.ProfileId).ToList();
        if (player.Games.Count > 0)
        {
          foreach (Game game in player.Games)
          {
            if (game.IsComplete == true)
            {
              completedGames += 1;
              if (player.ProfileId == game.WinningPlayer)
              {
                wins += 1;
              }
            }
          }
          if (completedGames > 0)
          {
            double division = (double)wins / (double)completedGames;
            int ratio = (int)(division * 100);
            leaders.Add(new KeyValuePair<string, int>(player.Name, ratio));
          }
        }
      }
      var sortedLeaders = from entry in leaders orderby entry.Value descending select entry;
      return View(sortedLeaders);
    }

    public async Task<IActionResult> Create()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      Profile currentProfile = _db.Profiles.FirstOrDefault(entry => entry.User == currentUser);
      ViewBag.ProfileId = currentProfile.ProfileId;
      return View();
    }

    [HttpPost]
    public ActionResult Create(Game game)
    {
      DateTime now = DateTime.Now;
      try
      {
        Profile playerTwo = _db.Profiles.FirstOrDefault(profile => profile.ProfileId == game.P2Id);
        Profile playerOne = _db.Profiles.FirstOrDefault(profile => profile.ProfileId == game.P1Id);
        game.LastPlayed = now;

        if (playerTwo != null && game.P1Id != game.P2Id)
        {
          game.P1Name = playerOne.Name;
          game.P2Name = playerTwo.Name;
          _db.Games.Add(game);
          _db.SaveChanges();
          return RedirectToAction("Details", new { id = game.GameId });
        }
        else
        {
          throw new System.InvalidOperationException("User unavailable");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }
    public ActionResult Details(int id)
    {
      Game thisGame = _db.Games.FirstOrDefault(game => game.GameId == id);

      Profile playerOne = _db.Profiles.FirstOrDefault(entry => entry.ProfileId == thisGame.P1Id);
      ViewBag.PlayerOne = playerOne;

      Profile playerTwo = _db.Profiles.FirstOrDefault(entry => entry.ProfileId == thisGame.P2Id);
      ViewBag.PlayerTwo = playerTwo;

      if (thisGame.IsComplete == true && thisGame.WinningPlayer == playerOne.ProfileId)
      {
        ViewBag.WinningName = playerOne.Name;
      }
      else if (thisGame.IsComplete == true && thisGame.WinningPlayer == playerTwo.ProfileId)
      {
        ViewBag.WinningName = playerTwo.Name;
      }
      return View(thisGame);
    }
    public ActionResult Error(string message)
    {
      return View(message);
    }


    public async Task<ActionResult> Turn(int id)
    {
      Game currentGame = _db.Games.FirstOrDefault(entry => entry.GameId == id);

      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      Profile currentProfile = _db.Profiles.FirstOrDefault(entry => entry.User == currentUser);

      string firstBoard = currentGame.P1Board;
      string secondBoard = currentGame.P2Board;

      int[,] p1Board = JsonConvert.DeserializeObject<int[,]>(firstBoard);
      int[,] p2Board = JsonConvert.DeserializeObject<int[,]>(secondBoard);

      Profile playerOne = _db.Profiles.FirstOrDefault(entry => entry.ProfileId == currentGame.P1Id);
      Profile playerTwo = _db.Profiles.FirstOrDefault(entry => entry.ProfileId == currentGame.P2Id);

      if (currentGame.P1Id == currentProfile.ProfileId)
      {
        ViewBag.P1Board = p1Board;
        ViewBag.P2Target = Game.Scrub(p2Board);
        ViewBag.CurrentView = 1;
        ViewBag.OpponentName = playerTwo.Name;
        ViewBag.OpponentImg = playerTwo.Img;
      }
      else if (currentGame.P2Id == currentProfile.ProfileId)
      {
        ViewBag.P2Board = p2Board;
        ViewBag.P1Target = Game.Scrub(p1Board);
        ViewBag.CurrentView = 2;
        ViewBag.OpponentName = playerOne.Name;
        ViewBag.OpponentImg = playerOne.Img;
      }


      if (currentGame.IsComplete == true && currentGame.WinningPlayer == playerOne.ProfileId)
      {
        ViewBag.WinningName = playerOne.Name;
      }
      else if (currentGame.IsComplete == true && currentGame.WinningPlayer == playerTwo.ProfileId)
      {
        ViewBag.WinningName = playerTwo.Name;
      }

      if ((currentGame.TurnCount % 2 == 1 && currentGame.P1Id == currentProfile.ProfileId) || (currentGame.TurnCount % 2 == 0 && currentGame.P2Id == currentProfile.ProfileId))
      {
        ViewBag.IsYourTurn = false;
      }
      else
      {
        ViewBag.IsYourTurn = true;
      }
      return View(currentGame);
    }

    [HttpPost]
    public ActionResult Play(int playerId, int gameId, int x, int y)
    {
      Game currentGame = _db.Games.FirstOrDefault(entry => entry.GameId == gameId);

      int[,] board = currentGame.TakeTurn(x, y, playerId);
      string boardJson = JsonConvert.SerializeObject(board);
      if (playerId == currentGame.P1Id)
      {
        currentGame.P2Board = boardJson;
        currentGame.CurrentPlayer = currentGame.P2Id;
      }
      else if (playerId == currentGame.P2Id)
      {
        currentGame.P1Board = boardJson;
        currentGame.CurrentPlayer = currentGame.P1Id;
      }
      currentGame.TurnCount++;

      _db.Entry(currentGame).State = EntityState.Modified;
      _db.SaveChanges();

      return RedirectToAction("Turn", new { id = gameId });
    }
  }
}

TreasureSweep/Controllers/ProfilesController.cs
using System;
using System.Linq;
using System.Data;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using TreasureSweepGame.Models;
using TreasureSweepGame.ViewModels;
using System.Collections.Generic;

namespace TeasureSweepGame.Controllers
{
  [Authorize]
  public class ProfilesController : Controller
  {
    private readonly TreasureSweepGameContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public ProfilesController(TreasureSweepGameContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    [AllowAnonymous]
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      List<Profile> results = _db.Profiles.ToList();
      Profile thisProfile = _db.Profiles.FirstOrDefault(entry => entry.User == currentUser);
      ViewBag.CurrentUserId = thisProfile.ProfileId;
      return View(results);
    }

    public async Task<ActionResult> Details()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      try
      {
        int wins = 0;
        int completedGames = 0;

        Profile thisProfile = _db.Profiles.FirstOrDefault(profile => profile.User == currentUser);
        thisProfile.Games = _db.Games.Where(game => game.P1Id == thisProfile.ProfileId || game.P2Id == thisProfile.ProfileId).OrderByDescending(entry => entry.LastPlayed).ToList();
        if (thisProfile.Games.Count > 0)
        {
          foreach (Game game in thisProfile.Games)
          {
            if (game.IsComplete == true)
            {
              completedGames += 1;
              if (thisProfile.ProfileId == game.WinningPlayer)
              {
                wins += 1;
              }
            }
          }
        }
        int losses = completedGames - wins;
        ViewBag.Losses = losses;
        ViewBag.Wins = wins;
        ViewBag.Profiles = _db.Profiles.ToList();
        return View(thisProfile);
      }
      catch (Exception)
      {
        return RedirectToAction("Create");
      }
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Profile profile)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      profile.User = currentUser;
      if (String.IsNullOrWhiteSpace(profile.Img))
      {
        profile.Img = "/img/rubber-ducky.png";
      }
      _db.Profiles.Add(profile);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id, string message)
    {
      Profile thisProfile = _db.Profiles.FirstOrDefault(profile => profile.ProfileId == id);
      if (message != null)
      {
        ViewBag.Message = message;
      }
      return View(thisProfile);
    }

    [HttpPost]
    public ActionResult Edit(Profile profile)
    {
      if (String.IsNullOrWhiteSpace(profile.Img))
      {
        profile.Img = "/img/rubber-ducky.png";
      }
      _db.Entry(profile).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details");
    }

    //search for profiles
    public async Task<ActionResult> Search(string playerName)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(playerName) == false)
        {
          string searchName = playerName.ToLower();
          List<Profile> results = _db.Profiles.Where(profile => profile.Name.ToLower().Contains(playerName)).ToList();
          if (results.Count == 0)
          {
            throw new System.InvalidOperationException("User not found");
          }
          var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
          var currentUser = await _userManager.FindByIdAsync(userId);
          Profile thisProfile = _db.Profiles.FirstOrDefault(entry => entry.User == currentUser);
          ViewBag.CurrentUserId = thisProfile.ProfileId;
          return View(results);
        }
        else
        {
          throw new System.InvalidOperationException("User not found");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }
  }
}

TreasureSweep/Views/Games/Create.cshtml
@using TreasureSweepGame.Models
@model TreasureSweepGame.Models.Game
@using System

<div class="col-md-6 offset-md-3">
  <h1>CREATE GAME</h1>
  @Html.ActionLink("SHOW ALL PLAYERS", "Index", "Profiles", null, new { @class="btn-block"})
  <hr />
  @using (Html.BeginForm())
  {
    <input type="hidden" value="@ViewBag.ProfileId" name="P1Id" id="P1Id">
    <input type="hidden" value="@ViewBag.ProfileId" name="CurrentPlayer" id="CurrentPlayer">
    <br>
    <h4 for="P2Id">SECOND PLAYER ID NUMBER:</h4>
    @Html.TextBoxFor(model => model.P2Id)
    <br>
    <button type="submit" class="btn-block">START NEW GAME</button>
  }
  <hr />
  <div class="playerSearchDiv text-center">
    <h4>SEARCH FOR FRIEND BY NAME</h4>
    @using(Html.BeginForm("Search", "Profiles"))
    {
      <input type="text" name="playerName" id="playerName">
      <button type="submit" class="btn-block">SEARCH FOR FRIEND</button>
    }
  </div>
</div>

TreasureSweep/Views/Games/Details.cshtml
@model TreasureSweepGame.Models.Game


<h1>GAME @Model.GameId DETAILS</h1>

<div class="row">
  <div class="col-md-6 text-center">
    <h4>Player 1: @ViewBag.PlayerOne.Name</h4>
    <img src="@ViewBag.PlayerOne.Img" alt="" class="profile-pic">
    <h4>@ViewBag.PlayerOne.TagLine</h4>
  </div>

  <div class="col-md-6 text-center">
    <h4>Player 2: @ViewBag.PlayerTwo.Name</h4>
    <img src="@ViewBag.PlayerTwo.Img" alt="" class="profile-pic">
    <h4>@ViewBag.PlayerTwo.TagLine</h4>
  </div>
</div>

<div class="row">

  <div class="col-md-6 offset-3 text-center">
  <h4>TURN #@Model.TurnCount</h4>
  @if(Model.TurnCount % 2 == 1 && Model.IsComplete == false)
  {
    <h4>@ViewBag.PlayerTwo.Name's Turn!</h4>
    @Html.ActionLink("Play Turn", "Turn", "Games", new {id = Model.GameId}, new { @class="btn"})
  }
  else if (Model.IsComplete == false)
  {
    <h4>@ViewBag.PlayerOne.Name's Turn!</h4>
    @Html.ActionLink("Play Turn", "Turn", "Games", new {id = Model.GameId}, new { @class="btn"})
  }
  else
  {
    <h1>@ViewBag.WinningName won!</h1>
    @Html.ActionLink("See Results", "Turn", "Games", new {id = Model.GameId}, new { @class="btn"})
  }
  </div>
</div>

TreasureSweep/Views/Games/Edit.cshtml
<h1>Edit Game</h1>

TreasureSweep/Views/Games/Index.cshtml
@using System;
@using System.Collections.Generic;
<h1>LEADERBOARD</h1>
<h2>ORDERED BY PERCENTAGE OF GAMES WON</h2>
<table>
  <tr>
    <th>USERNAME</th>
    <th>WINS/GAMES COMPLETED</th>
  </tr>
@foreach(KeyValuePair<string, int> leader in Model)
{
  <tr>
    <td>@leader.Key</td>
    <td>@leader.Value%</td>
  </tr>
}
</table>

TreasureSweep/Views/Games/Turn.cshtml
<div class="row">
  @if (ViewBag.CurrentView == 1)
  {
    <div class="col-md-7">
      @await Html.PartialAsync("_P2TargetBoard")
    </div>
    <div class="col-md-5">
      @await Html.PartialAsync("_P1Look")
    </div>
  }
  else if (ViewBag.CurrentView == 2)
  {
    <div class="col-md-7">
      @await Html.PartialAsync("_P1TargetBoard")
    </div>
    <div class="col-md-5">
      @await Html.PartialAsync("_P2Look")
    </div>
  }
</div>
<div class="row">
  <div class="col-md-12">
    @if (ViewBag.IsYourTurn && @Model.IsComplete == false)
    {
      <h1> IT'S YOUR TURN </h1>
    }
    else if (@Model.IsComplete == false)
    {
      <h1>WAITING FOR YOUR OPPONENT...</h1>
    }
    else if (@Model.IsComplete) 
    {
      <h1>@ViewBag.WinningName WON!</h1>
      <h1>GAME OVER </h1>
    }
  </div>
</div>

<script src="~/js/autoRefresh.js"></script>

TreasureSweep/Views/Games/_P1Look.cshtml
<h1 class="beach-header"> OPPONENT'S PROGRESS </h1>
<div id="p1board">
  @for (int x = 0; x <= 4 ; x++)
  {
    @for (int y = 0; y <= 4 ; y++)
    {
      if(ViewBag.P1Board[x,y] == 0)
      {
        <img src="/img/sand.png" alt="sand">
      }
      else if(ViewBag.P1Board[x,y] == 1)
      {
        <img src="/img/chest-closed.png" alt="hidden treasure">
      }
      else if(ViewBag.P1Board[x,y] == 2)
      {
        <img src="/img/sand-bomb.png" alt="burried bomb">
      }
      else if (ViewBag.P1Board[x,y] == 3)
      {
        <img src="/img/miss.png" alt="miss">
      }
      else if(ViewBag.P1Board[x,y] == 4)
      {
        <img src="/img/chest-open.png" alt="uncovered treasure">
      }
      else if(ViewBag.P1Board[x,y] == 5)
      {
        <img src="/img/sand-boom.png" alt="exploded bomb">
      }
    }   
  }
</div>
<div class="opponentDiv">
  <img src="@ViewBag.OpponentImg" />
  <h2>@ViewBag.OpponentName</h2>
</div>

TreasureSweep/Views/Games/_P1TargetBoard.cshtml
<h1 class="beach-header"> FIND OPPONENT'S TREASURE </h1>
<div id="p1target">
  @for (int x = 0; x <= 4; x++)
  {
    @for (int y = 0; y <= 4; y++)
    {
      if(ViewBag.P1Target[x,y] == 0)
      {
        if (ViewBag.IsYourTurn && Model.IsComplete == false)
        {
          @using (Html.BeginForm("Play", "Games", FormMethod.Post))
          {
            <input type="hidden" name="playerId" id="playerId" value="@Model.P2Id">
            <input type="hidden" name="gameId" id="gameId" value="@Model.GameId">
            <input type="hidden" name="x" id="x" value="@x">
            <input type="hidden" name="y" id="y" value="@y">
            <button type="submit" class="sand"></button>
          }
        }
        else
        {
          <img src="/img/sand.png" alt="sand">
        }
      }
      else if (ViewBag.P1Target[x,y] == 3)
      {
        <img src="/img/miss.png" alt="miss">
      }
      else if(ViewBag.P1Target[x,y] == 4)
      {
        <img src="/img/chest-open.png" alt="uncovered treasure">
      }
      else if(ViewBag.P1Target[x,y] == 5)
      {
        <img src="/img/sand-boom.png" alt="exploded bomb">
      }
    }   
  }
</div>

TreasureSweep/Views/Games/_P2Look.cshtml
<h1 class="beach-header"> OPPONENT'S PROGRESS </h1>
<div id="p2board">
  @for (int x = 0; x <= 4 ; x++)
  {
    @for (int y = 0; y <= 4 ; y++)
    {
      if(ViewBag.P2Board[x,y] == 0)
      {
        <img src="/img/sand.png" alt="sand">
      }
      else if(ViewBag.P2Board[x,y] == 1)
      {
        <img src="/img/chest-closed.png" alt="hidden treasure">
      }
      else if(ViewBag.P2Board[x,y] == 2)
      {
        <img src="/img/sand-bomb.png" alt="burried bomb">
      }
      else if (ViewBag.P2Board[x,y] == 3)
      {
        <img src="/img/miss.png" alt="miss">
      }
      else if(ViewBag.P2Board[x,y] == 4)
      {
        <img src="/img/chest-open.png" alt="uncovered treasure">
      }
      else if(ViewBag.P2Board[x,y] == 5)
      {
        <img src="/img/sand-boom.png" alt="exploded bomb">
      }
    }   
  }
</div>
<div class="opponentDiv">
  <img src="@ViewBag.OpponentImg" />
  <h2>@ViewBag.OpponentName</h2>
</div>

TreasureSweep/Views/Games/_P2TargetBoard.cshtml
<h1 class="beach-header"> FIND OPPONENT'S TREASURE </h1>
<div id="p2target">
  @for (int x = 0; x <= 4; x++)
  {
    @for (int y = 0; y <= 4; y++)
    {
      if(ViewBag.P2Target[x,y] == 0)
      {
        if (ViewBag.IsYourTurn && Model.IsComplete == false)
        {
          @using (Html.BeginForm("Play", "Games", FormMethod.Post))
          {
            <input type="hidden" name="playerId" id="playerId" value="@Model.P1Id">
            <input type="hidden" name="gameId" id="gameId" value="@Model.GameId">
            <input type="hidden" name="x" id="x" value="@x">
            <input type="hidden" name="y" id="y" value="@y">
            <button type="submit" class="sand"></button>
          }
        }
        else
        {
          <img src="/img/sand.png" alt="sand">
        }
      }
      else if (ViewBag.P2Target[x,y] == 3)
      {
        <img src="/img/miss.png" alt="miss">
      }
      else if(ViewBag.P2Target[x,y] == 4)
      {
        <img src="/img/chest-open.png" alt="uncovered treasure">
      }
      else if(ViewBag.P2Target[x,y] == 5)
      {
        <img src="/img/sand-boom.png" alt="exploded bomb">
      }
    }   
  }
</div>